[package]
name = "rpi_gpu_game"
version = "0.1.0"
authors = ["Jonathan"]
edition = "2018"

[dependencies]
byteorder = "1"
lazy_static = "1"
libc = "0.2"
nix = "0.13"
static_assertions = "0.3"
structview = "0.1"